polling_app/urls.py
import debug_toolbar
from django.urls import include, path
from rest_framework.routers import DefaultRouter
from . import views
from polls.views import QuestionViewSet, ChoiceViewSet

router = DefaultRouter()

router.register(r'question', QuestionViewSet, basename='question')
router.register(r'choice', ChoiceViewSet, basename='choice')


urlpatterns = [
    path('', views.index, name='index'),
    path('polls/', include('polls.urls')),
    path('api/polls/', include(router.urls)),
    path('__debug__/', include(debug_toolbar.urls)),
]

polls/urls.py
from django.urls import path

from polls.views import index, detail, results, vote

app_name = 'polls'

urlpatterns = [
    # ex: /polls/
    path('', index, name='index'),
    # ex: /polls/5/
    path('<int:question_id>/', detail, name='detail'),
    # ex: /polls/5/results/
    path('<int:question_id>/results/', results, name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', vote, name='vote'),
]

polls/models.py
import datetime

from django.db import models
from django.utils import timezone

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polling_app/views.py
from django.shortcuts import get_object_or_404, render

def index(request):
    return render(request, 'index.html')

polls/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from .models import Question, Choice
from .serializers import QuestionSerializer, ChoiceSerializer
from rest_framework import viewsets


class QuestionViewSet(viewsets.ModelViewSet):
    serializer_class = QuestionSerializer
    queryset = Question.objects.all()


class ChoiceViewSet(viewsets.ModelViewSet):
    serializer_class = ChoiceSerializer
    queryset = Choice.objects.all()


def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'polls/index.html', context)


def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

polling_app/templates/index.html
{% load static %}
<title>AXI Project</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">

<header class="header">
  <a href="{% url 'polls:index' %}" class="header-link">View Polls</a>
</header>

<section class="landing-section landing-main">
  <div class="landing-section-content">
    <h1 class="brand">polling_app</h1>
    <p class="landing-main-text">
      A public site that lets people view polls and vote in them.
      <br><br>
      Check out all current polls by clicking on "View Polls" (top-right)
    </p>
  </div>
</section>

<!--<!DOCTYPE html>-->
<!--<html lang="en">-->
<!--<head>-->
<!--    <meta charset="UTF-8">-->
<!--    <meta name="viewport" content="width=device-width, initial-scale=1">-->
<!--    <title>Title</title>-->

<!--        {% load static %}-->
<!--    <link rel="stylesheet" type="text/css" href="{% static './style.css' %}">-->

<!--</head>-->
<!--<body>-->
<!--    <header class="header">-->
<!--      <a href="#" class="header-link">View Polls</a>-->
<!--      <a href="#" class="header-link">View Results</a>-->
<!--    </header>-->

<!--    <section>-->
<!--      <h1 class="brand">polling_app</h1>-->
<!--      <p class="landing-main-text">-->
<!--        A public site that lets people view polls and vote in them.-->
<!--      </p>-->
<!--    </section>-->
<!--</body>-->
<!--</html>-->

polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>

polls/templates/polls/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>